import { PDFDocument, rgb, StandardFonts, type PDFFont, type PDFPage } from "pdf-lib";
import {
  CLINIC_ADDRESS,
  CLINIC_EMAIL,
  CLINIC_GSTIN,
  CLINIC_HOURS,
  CLINIC_NAME,
  CLINIC_PHONE,
  CLINIC_WEBSITE,
} from "@clinic/shared";
import { CLINIC_LOGO_PNG_BASE64 } from "../assets/clinicLogo.js";

const PAGE_WIDTH = 595.28; // A4, points
const PAGE_HEIGHT = 841.89;
const MARGIN = 48;
const LOGO_SIZE = 64;
const BRAND_BLUE = rgb(0.29, 0.45, 0.75); // sampled from the real clinic logo
const DARK = rgb(0.13, 0.15, 0.18);
const GRAY = rgb(0.45, 0.47, 0.5);
const LIGHT_LINE = rgb(0.85, 0.86, 0.88);
const GREEN = rgb(0.1, 0.55, 0.3);
const AMBER = rgb(0.75, 0.5, 0.05);

export interface InvoicePdfItem {
  description: string;
  amount: number;
}

export interface InvoicePdfInput {
  invoiceId: string;
  date: string; // ISO
  status: string;
  patientName: string;
  patientPhone: string;
  items: InvoicePdfItem[];
  totalAmount: number;
  amountPaid: number;
  /** Name of the staff account that created the invoice; omitted (legacy rows, or a deleted account) leaves the footer credit off. */
  generatedByName?: string | null;
  /** Doctor(s) who performed the billed treatment(s), resolved from the line items' linked treatment records. Empty when no item is tied to one (e.g. a standalone consultation fee). */
  treatedByNames?: string[];
}

/**
 * pdf-lib's standard fonts use WinAnsi encoding, which has no glyph for "₹"
 * (Rupee sign) - drawText would throw. "Rs." is the safe, universally
 * understood substitute rather than embedding a whole custom Unicode font
 * just for one symbol.
 */
function formatMoney(amount: number): string {
  return `Rs. ${amount.toFixed(2)}`;
}

function shortInvoiceNumber(invoiceId: string): string {
  return `INV-${invoiceId.replace(/-/g, "").slice(0, 8).toUpperCase()}`;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric", timeZone: "Asia/Kolkata" });
}

function statusLabel(status: string): { text: string; color: ReturnType<typeof rgb> } {
  if (status === "paid") return { text: "PAID", color: GREEN };
  if (status === "cancelled") return { text: "CANCELLED", color: GRAY };
  if (status === "partially_paid") return { text: "PARTIALLY PAID", color: AMBER };
  return { text: "UNPAID", color: AMBER };
}

/**
 * Where the full-width clinic detail lines and the divider sit, in points
 * below the top margin. Kept below HEADER_TOP_ZONE_BOTTOM (where the
 * invoice #/date/status column finishes) so a long line here - the address
 * is 80+ characters - can never run into that right-aligned text, whatever
 * its exact rendered width turns out to be.
 */
const HEADER_TOP_ZONE_BOTTOM = 44;
const ADDRESS_Y = 62;
const CONTACT_Y = 76;
const WEBSITE_Y = 90;
const GSTIN_Y = 104;
const DIVIDER_Y = 122;

/** Renders the fixed page furniture (logo, letterhead, footer) that every page of a multi-page invoice repeats. */
function drawPageChrome(
  page: PDFPage,
  logo: Awaited<ReturnType<PDFDocument["embedPng"]>>,
  fontBold: PDFFont,
  font: PDFFont,
  generatedByName?: string | null,
) {
  const top = PAGE_HEIGHT - MARGIN;
  const textX = MARGIN + LOGO_SIZE + 14;
  page.drawImage(logo, { x: MARGIN, y: top - LOGO_SIZE + 8, width: LOGO_SIZE, height: LOGO_SIZE });
  // Kept at the original 13pt (not enlarged along with the logo): at 15pt this
  // string's real pdf-lib-measured width runs into the invoice number's
  // right-aligned column above the fold; 13pt leaves a clear ~30pt gap.
  page.drawText(CLINIC_NAME, { x: textX, y: top - 8, size: 13, font: fontBold, color: DARK });
  page.drawText("Unleash Confident Smiles", { x: textX, y: top - 24, size: 9, font, color: GRAY });

  // Full-width from here down - see HEADER_TOP_ZONE_BOTTOM above.
  page.drawText(CLINIC_ADDRESS, { x: textX, y: top - ADDRESS_Y, size: 8.5, font, color: GRAY, maxWidth: PAGE_WIDTH - MARGIN - textX });
  page.drawText(`Phone: ${CLINIC_PHONE}   |   Email: ${CLINIC_EMAIL}`, { x: textX, y: top - CONTACT_Y, size: 8.5, font, color: GRAY });
  page.drawText(`${CLINIC_WEBSITE}   |   Timings: ${CLINIC_HOURS}`, { x: textX, y: top - WEBSITE_Y, size: 8.5, font, color: GRAY });
  page.drawText(`GSTIN: ${CLINIC_GSTIN}`, { x: textX, y: top - GSTIN_Y, size: 8.5, font, color: GRAY });

  if (generatedByName) {
    page.drawText(`Invoice generated by ${generatedByName}`, {
      x: MARGIN,
      y: MARGIN + 12,
      size: 7.5,
      font,
      color: GRAY,
    });
  }
  page.drawText("Thank you for visiting Dr.Sri Sushma Multispeciality Dental Clinic.", {
    x: MARGIN,
    y: MARGIN,
    size: 7.5,
    font,
    color: GRAY,
  });
  page.drawText("This is a system-generated invoice and does not require a signature.", {
    x: MARGIN,
    y: MARGIN - 12,
    size: 7.5,
    font,
    color: GRAY,
  });
}

export async function generateInvoicePdf(input: InvoicePdfInput): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const logoBytes = Uint8Array.from(atob(CLINIC_LOGO_PNG_BASE64), (c) => c.charCodeAt(0));
  const logo = await pdfDoc.embedPng(logoBytes);

  let page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  drawPageChrome(page, logo, fontBold, font, input.generatedByName);

  const rightColX = PAGE_WIDTH - MARGIN;
  const top = PAGE_HEIGHT - MARGIN;
  const invoiceNo = shortInvoiceNumber(input.invoiceId);
  const invoiceNoWidth = fontBold.widthOfTextAtSize(invoiceNo, 18);
  page.drawText(invoiceNo, { x: rightColX - invoiceNoWidth, y: top - 10, size: 18, font: fontBold, color: BRAND_BLUE });
  const dateText = formatDate(input.date);
  const dateWidth = font.widthOfTextAtSize(dateText, 10);
  page.drawText(dateText, { x: rightColX - dateWidth, y: top - 26, size: 10, font, color: GRAY });
  const { text: statusText, color: statusColor } = statusLabel(input.status);
  const statusWidth = fontBold.widthOfTextAtSize(statusText, 10);
  page.drawText(statusText, { x: rightColX - statusWidth, y: top - HEADER_TOP_ZONE_BOTTOM, size: 10, font: fontBold, color: statusColor });

  let y = top - DIVIDER_Y;
  page.drawLine({ start: { x: MARGIN, y }, end: { x: rightColX, y }, thickness: 1, color: LIGHT_LINE });
  y -= 24;

  const treatedByX = MARGIN + 280;
  const hasTreatedBy = !!input.treatedByNames && input.treatedByNames.length > 0;
  page.drawText("BILLED TO", { x: MARGIN, y, size: 8, font: fontBold, color: GRAY });
  if (hasTreatedBy) {
    page.drawText("TREATED BY", { x: treatedByX, y, size: 8, font: fontBold, color: GRAY });
  }
  y -= 16;
  page.drawText(input.patientName, { x: MARGIN, y, size: 12, font: fontBold, color: DARK });
  if (hasTreatedBy) {
    page.drawText(input.treatedByNames!.join(", "), { x: treatedByX, y, size: 12, font: fontBold, color: DARK, maxWidth: rightColX - treatedByX });
  }
  y -= 15;
  page.drawText(input.patientPhone, { x: MARGIN, y, size: 10, font, color: GRAY });
  y -= 30;

  const descColX = MARGIN;
  const amountColX = rightColX;
  page.drawRectangle({ x: MARGIN, y: y - 6, width: rightColX - MARGIN, height: 22, color: rgb(0.95, 0.96, 0.98) });
  page.drawText("DESCRIPTION", { x: descColX + 8, y: y, size: 8.5, font: fontBold, color: GRAY });
  const amountHeaderWidth = fontBold.widthOfTextAtSize("AMOUNT", 8.5);
  page.drawText("AMOUNT", { x: amountColX - amountHeaderWidth - 8, y: y, size: 8.5, font: fontBold, color: GRAY });
  y -= 28;

  const bottomLimit = MARGIN + 40;
  for (const item of input.items) {
    if (y < bottomLimit) {
      page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      drawPageChrome(page, logo, fontBold, font, input.generatedByName);
      y = top - (DIVIDER_Y + 20);
    }
    page.drawText(item.description, { x: descColX + 8, y, size: 10.5, font, color: DARK, maxWidth: 340 });
    const amountText = formatMoney(item.amount);
    const amountWidth = font.widthOfTextAtSize(amountText, 10.5);
    page.drawText(amountText, { x: amountColX - amountWidth - 8, y, size: 10.5, font, color: DARK });
    y -= 12;
    page.drawLine({ start: { x: MARGIN, y }, end: { x: rightColX, y }, thickness: 0.5, color: LIGHT_LINE });
    y -= 18;
  }

  if (y < bottomLimit + 70) {
    page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
    drawPageChrome(page, logo, fontBold, font, input.generatedByName);
    y = top - (DIVIDER_Y + 20);
  }

  y -= 10;
  const balanceDue = Math.max(0, input.totalAmount - input.amountPaid);
  const totalsRow = (label: string, amount: number, opts?: { bold?: boolean; color?: ReturnType<typeof rgb> }) => {
    const labelFont = opts?.bold ? fontBold : font;
    const color = opts?.color ?? DARK;
    const amountText = formatMoney(amount);
    const amountWidth = labelFont.widthOfTextAtSize(amountText, 11);
    page.drawText(label, { x: rightColX - 180, y, size: 11, font: labelFont, color });
    page.drawText(amountText, { x: rightColX - amountWidth, y, size: 11, font: labelFont, color });
    y -= 18;
  };
  totalsRow("Total", input.totalAmount);
  totalsRow("Paid", input.amountPaid);
  page.drawLine({ start: { x: rightColX - 180, y: y + 6 }, end: { x: rightColX, y: y + 6 }, thickness: 0.75, color: LIGHT_LINE });
  totalsRow("Balance due", balanceDue, { bold: true, color: balanceDue > 0 ? AMBER : GREEN });

  return pdfDoc.save();
}
