import { inflateSync } from "node:zlib";
import { describe, expect, it } from "vitest";
import { amountInWords, generateInvoicePdf } from "../src/lib/invoicePdf.js";

const BASE_INPUT = {
  invoiceId: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  date: "2026-10-05T09:30:00.000Z",
  patientName: "Asha Rao",
  patientPhone: "9876543210",
  items: [{ description: "Scaling and polishing", amount: 1500 }],
  totalAmount: 1500,
  amountPaid: 0,
};

function isPdf(bytes: Uint8Array): boolean {
  return new TextDecoder().decode(bytes.slice(0, 5)) === "%PDF-";
}

/**
 * pdf-lib saves every drawn string as a hex string (`<...> Tj`) inside a
 * Flate-compressed content stream, even for plain ASCII - so a raw byte
 * search for e.g. "Invoice generated by" never matches. This inflates every
 * `stream...endstream` block it can and hex-decodes the text-show operators,
 * giving back the actual drawn text for a real presence assertion.
 */
function extractPdfText(bytes: Uint8Array): string {
  const raw = Buffer.from(bytes).toString("latin1");
  let inflated = "";
  for (const [, body] of raw.matchAll(/stream\r?\n([\s\S]*?)endstream/g)) {
    try {
      // Buffer.from(...) here, not a bare inflateSync(...).toString(encoding):
      // apps/api's tsconfig only brings in @cloudflare/workers-types (no
      // @types/node), under which inflateSync()'s declared return type has a
      // 0-arg toString() - wrapping it back through Buffer.from(...) gets a
      // type whose toString(encoding) actually type-checks, for a value that
      // is a real Node Buffer at runtime either way (plain-Node vitest, see
      // vitest.config.ts).
      inflated += Buffer.from(inflateSync(Buffer.from(body, "latin1"))).toString("latin1");
    } catch {
      // Not a Flate-encoded stream (e.g. raw image data) - nothing to read here.
    }
  }
  let text = "";
  for (const [, hex] of inflated.matchAll(/<([0-9A-Fa-f]+)>\s*Tj/g)) {
    text += Buffer.from(hex, "hex").toString("latin1");
  }
  return text;
}

describe("generateInvoicePdf", () => {
  it("produces valid PDF bytes", async () => {
    const bytes = await generateInvoicePdf({ ...BASE_INPUT, status: "unpaid" });
    expect(isPdf(bytes)).toBe(true);
    expect(bytes.length).toBeGreaterThan(1000);
  });

  it("does not throw for every invoice status", async () => {
    for (const status of ["unpaid", "partially_paid", "paid", "cancelled"]) {
      const bytes = await generateInvoicePdf({ ...BASE_INPUT, status });
      expect(isPdf(bytes)).toBe(true);
    }
  });

  it("does not throw with no line items", async () => {
    const bytes = await generateInvoicePdf({ ...BASE_INPUT, status: "unpaid", items: [], totalAmount: 0 });
    expect(isPdf(bytes)).toBe(true);
  });

  it("paginates onto a second page rather than throwing when there are many line items", async () => {
    const items = Array.from({ length: 60 }, (_, i) => ({ description: `Procedure ${i + 1}`, amount: 100 }));
    const bytes = await generateInvoicePdf({ ...BASE_INPUT, status: "unpaid", items, totalAmount: 6000 });
    expect(isPdf(bytes)).toBe(true);
  });

  it("never renders the raw rupee sign, which standard PDF fonts can't encode", async () => {
    const bytes = await generateInvoicePdf({ ...BASE_INPUT, status: "unpaid" });
    const text = new TextDecoder("latin1").decode(bytes);
    expect(text).not.toContain("₹");
  });

  it("renders the clinic GSTIN on every invoice", async () => {
    const bytes = await generateInvoicePdf({ ...BASE_INPUT, status: "unpaid" });
    expect(extractPdfText(bytes)).toContain("GSTIN: 36APBPY6938F1ZF");
  });

  it("credits the generating staff member when given a name", async () => {
    const bytes = await generateInvoicePdf({ ...BASE_INPUT, status: "unpaid", generatedByName: "Dr.Sri Sushma" });
    expect(extractPdfText(bytes)).toContain("Invoice generated by Dr.Sri Sushma");
  });

  it("prints the requested columns, unit cost, payment details, words and instructions", async () => {
    const bytes = await generateInvoicePdf({
      ...BASE_INPUT,
      status: "paid",
      items: [{ description: "Laser Scaling", amount: 4000, units: 2 }],
      totalAmount: 4000,
      amountPaid: 4000,
      payments: [{ method: "amazon_pay", amount: 4000 }],
      instructions: "Review after seven days.",
    });
    const rendered = extractPdfText(bytes);
    for (const value of ["S.No", "Procedure", "Type", "Particulars", "Cost", "Units", "Net Amt", "Gross", "Laser Scaling", "2,000.00", "4,000.00", "Payment Details:", "By Amazon Pay:", "Four Thousand Indian Rupees Only", "Review after seven days."]) {
      expect(rendered).toContain(value);
    }
  });

  it("uses Indian amount names and includes paise", () => {
    expect(amountInWords(6000)).toBe("Six Thousand Indian Rupees Only");
    expect(amountInWords(123456.25)).toBe("One Lakh Twenty Three Thousand Four Hundred Fifty Six Indian Rupees and Twenty Five Paise Only");
  });

  it("does not throw when generatedByName is omitted (legacy invoices, deleted accounts)", async () => {
    const bytes = await generateInvoicePdf({ ...BASE_INPUT, status: "unpaid", generatedByName: null });
    expect(isPdf(bytes)).toBe(true);
    expect(extractPdfText(bytes)).not.toContain("Invoice generated by");
  });
});
